spring:
  datasource:
    url: jdbc:mysql://localhost:3306/candidateDB?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: kamdem.guy@institutsaintjean.org
    password: osurrusawvgooxam
    properties:
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

application:
  security:
    jwt:
      secret-key: 738715c8951bde192826ac2e9b387f56ad157fbc6dbc93947811bc468925f368
      expiration: 8640000
  mailing:
    frontend:
      activation-url : http://20.11.21.61:4200/avtivate-account
      resetUrl : http://20.11.21.61:4200/resertUrl
server:
  port: 8087